### ISSUE TITLE
Why using tinyurl? Seems unnecessary

### ISSUE THREAD

**Issue by Henriquelay** [okhwaja/outline-extension#16]
First of all, this is best placed in a Discussions tab, but since it's turned off, I opened this.

https://github.com/okhwaja/outline-extension/blob/3e10446b63ed53b0166f83dd1a17b760d27a3f00/background.js#L40
It adds a delay to redirect us to the next page, whilst adding tinyurl API as a dependency. Does the mantainers even make some cash out of this? I'm cool with that, I'd just like to know, and don't see any tinyurl api key loading or passing to the request, so I guess it's not the case.
Some times, specially while under a VPN and on mobile, this takes a long time to open a new tab with essentially just prefixing `outline.com/` before should take.

**Comment by cmalard** [comment]
[Seems to be](https://addons.mozilla.org/fr/firefox/addon/send-to-outline/reviews/1446636/) because some websites are *protected* by Outline. TinyUrl "obfsucates" the url so it does the trick ^^
Like https://outline.com/https://www.nytimes.com/2022/01/13/us/politics/supreme-court-biden-vaccine-mandate.html to redirects to https://outline.com/not_supported
Through TinyUrl: https://outline.com/https://tinyurl.com/vkzcb59n :magic_wand:

**Comment by Henriquelay** [comment]
That's it, thanks!
